### ISSUE TITLE
Missing data?

### ISSUE THREAD

**Issue by yoavram** [ydiekmann/Evershed_Nature_2022#1]
The ancient DNA genotype data file (AADRv44.subset.MPI Leila.tab)is missing values - or else I am missing something. The paper has genotype data up to 2000AD (0BP) but the data file column 'mean_date' goes from 2500 to 8000. I assume it is in BP, or BC, but I don't see how it covers 10000 years. I attempted to fit the constant selection model and the max likelihood estimate is s=0, probably because of the missing data, although I cannot be certain. 
I also counted the number of individuals and alleles, and I arrive at 1293 and 2586, whereas the paper says 1770 and 3057 (98+2959) in Fig 3. 

Help would be appreciated.

**Comment by ydiekmann** [comment]
Dear Yoav,
indeed, the file 'AADRv44.subset.mpileups.tsv' contains alleles only from individuals dated to 2500 to 8000 BP and found in regions denoted as 'British Isles', 'Baltic region', 'Rhine Danube axis', and 'Mediterranean Europe' in Figure 3, as that time span and these regions were the only ones for which we could generate the ecological proxy time series. I have now uploaded the file 'AADRv44.all.mpileups.tsv', which has all the data that went into generating Figure 3.
Best,
Yoan
